GET http://localhost:8000/api/v1/students

###

GET http://localhost:8000/api/v1/students/69114088f6800818904d8367

###

POST http://localhost:8000/api/v1/students
Content-Type: application/json

{
   "name": "Tony Stark",
   "class": "DWA"
}


###

DELETE http://localhost:8000/api/v1/students/690ea0b66ce3d463665cf2d5

###

PATCH http://localhost:8000/api/v1/students/69114088f6800818904d8367
Content-Type: application/json

{
   "name": "Bruce Wayne",
   "class": "NWA"
}